### ISSUE TITLE
Kompilierung schlägt fehl

### ISSUE THREAD

**Issue by quantenzitrone** [gitbuch/gitschulung_cc#6]
```py
$ make pdf
[ -s session_1.wiki ] && ./wiki2beamer < session_1.wiki > session_1.tex
Traceback (most recent call last):
  File "/data/documents/programming/github.com/gitschulung_cc/folien/./wiki2beamer", line 1122, in <module>
    main(sys.argv)
  File "/data/documents/programming/github.com/gitschulung_cc/folien/./wiki2beamer", line 1117, in main
    lines = convert2beamer(lines)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/data/documents/programming/github.com/gitschulung_cc/folien/./wiki2beamer", line 951, in convert2beamer
    out = convert2beamer_full(lines)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/documents/programming/github.com/gitschulung_cc/folien/./wiki2beamer", line 1066, in convert2beamer_full
    result.append(transform(line, state))
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/documents/programming/github.com/gitschulung_cc/folien/./wiki2beamer", line 453, in transform
    string = transform_uncover(string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/documents/programming/github.com/gitschulung_cc/folien/./wiki2beamer", line 421, in transform_uncover
    string = p.sub(r"\uncover<\1>{\2", string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lpi16513bai8kg2bd841745vzk72475x-python3-3.11.9/lib/python3.11/re/__init__.py", line 317, in _subx
    template = _compile_repl(template, pattern)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lpi16513bai8kg2bd841745vzk72475x-python3-3.11.9/lib/python3.11/re/__init__.py", line 308, in _compile_repl
    return _parser.parse_template(repl, pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/lpi16513bai8kg2bd841745vzk72475x-python3-3.11.9/lib/python3.11/re/_parser.py", line 1087, in parse_template
    raise s.error('bad escape %s' % this, len(this)) from None
re.error: bad escape \u at position 0
make: *** [Makefile:19: session1] Error 1
```

Meine erste Vermutung ist, dass es sich um Python-Versionsproblem handelt, ich weiß es aber nicht.
Ich bin auf Python 3.11.9.

**Comment by esc** [comment]
> Meine erste Vermutung ist, dass es sich um Python-Versionsproblem handelt, ich weiß es aber nicht. Ich bin auf Python 3.11.9.

Das ist eine valide Vermutung. Die Kopie von `wiki2beamer` in dem Repo ist ja auch schon sehr alt. Du könntest versuchen die Version hier zu verwenden (wobei die zuletzt noch unter Python 3.7 lief...):

https://github.com/wiki2beamer/wiki2beamer

Sonst könnte es auch ein einfaches encoding problem sein? Musst du mal gucken.

Wenn du schaffst es zum Laufen zu bekommen würde ich mich über einen Pull-Request freuen.

PS: Ich glaube ich habe die Folien Anfang 2021 noch verwendet, es gibt also durchaus Hoffnung.

**Comment by esc** [comment]
@quantenzitrone fix ist unter #7 verfügbar -- kannst du bestätigen das es auch für dich funktioniert?

**Comment by esc** [comment]
Fixed by #7
